# Generated by Django 3.1.1 on 2020-09-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psupplier', models.CharField(max_length=30)),
                ('psupplier_contact', models.CharField(max_length=20)),
                ('pproduct_category', models.CharField(max_length=30)),
                ('pproduct_brand', models.CharField(max_length=30)),
                ('pproduct_name', models.CharField(max_length=30)),
                ('pquantity', models.IntegerField()),
                ('peach_price', models.FloatField()),
                ('ptotal_price', models.FloatField()),
                ('ppurchase_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbuyer', models.CharField(max_length=30)),
                ('sbuyer_contact', models.CharField(max_length=20)),
                ('sproduct_category', models.CharField(max_length=30)),
                ('sproduct_brand', models.CharField(max_length=30)),
                ('sproduct_name', models.CharField(max_length=30)),
                ('squantity', models.IntegerField()),
                ('seach_price', models.FloatField()),
                ('stotal_price', models.FloatField()),
                ('ssale_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='Stock_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soproduct_category', models.CharField(max_length=30)),
                ('soproduct_brand', models.CharField(max_length=30)),
                ('soproduct_name', models.CharField(max_length=30)),
                ('soquantity', models.IntegerField()),
                ('soeach_price', models.FloatField()),
            ],
            options={
                'db_table': 'stock_out',
            },
        ),
        migrations.CreateModel(
            name='Stored_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spproduct_category', models.CharField(max_length=30)),
                ('spproduct_brand', models.CharField(max_length=30)),
                ('spproduct_name', models.CharField(max_length=30)),
                ('spquantity', models.IntegerField()),
                ('speach_price', models.FloatField()),
            ],
            options={
                'db_table': 'stored_product',
            },
        ),
    ]
