# Generated by Django 3.1.1 on 2020-09-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psupplier', models.CharField(max_length=30)),
                ('psupplier_contact', models.CharField(max_length=20)),
                ('pproduct_category', models.CharField(max_length=30)),
                ('pproduct_brand', models.CharField(max_length=30)),
                ('pproduct_name', models.CharField(max_length=30)),
                ('pproduct', models.CharField(max_length=30)),
                ('pquantity', models.IntegerField()),
                ('peach_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ptotal_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ppurchase_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
